import '../models/order_model.dart';

class OrderCatalogService {
  static const String purva = 'Purva Enterprises';
  static const String manas = 'Manas Sales';

  // Companies by Firm
  static const Map<String, List<String>> companiesByFirm = {
    purva: ['Wipro', 'Fena', 'Funfood', 'Imami'],
    manas: ['Racket', 'Imami', 'Dabar', 'Cadbury', 'Gowardhan'],
  };

  // Full product catalog
  static const List<CatalogProduct> catalog = [
    // ==========================================
    // PURVA ENTERPRISES - WIPRO
    // ==========================================
    CatalogProduct(
      id: 'wip-soap-1',
      name: 'Handwash (Santoor Pump)',
      category: 'Soap',
      company: 'Wipro',
      firm: purva,
      packing: '250ml Pump',
      mrp: 99.0,
      rate: 75.0,
    ),
    CatalogProduct(
      id: 'wip-soap-2',
      name: 'Handwash (Santoor Refill)',
      category: 'Soap',
      company: 'Wipro',
      firm: purva,
      packing: '180ml Pouch',
      mrp: 55.0,
      rate: 42.0,
    ),
    CatalogProduct(
      id: 'wip-soap-3',
      name: 'Santoor Sandal & Turmeric Soap',
      category: 'Soap',
      company: 'Wipro',
      firm: purva,
      packing: '100g Bar',
      mrp: 40.0,
      rate: 32.0,
    ),
    CatalogProduct(
      id: 'wip-soap-4',
      name: 'Santoor Soap (Buy 3 Get 1)',
      category: 'Soap',
      company: 'Wipro',
      firm: purva,
      packing: '125g x 4',
      mrp: 160.0,
      rate: 130.0,
    ),
    CatalogProduct(
      id: 'wip-soap-5',
      name: 'Chandrika Ayurvedic Soap',
      category: 'Soap',
      company: 'Wipro',
      firm: purva,
      packing: '75g Bar',
      mrp: 35.0,
      rate: 28.0,
    ),
    CatalogProduct(
      id: 'wip-pc-1',
      name: 'Santoor Body Lotion',
      category: 'Personal Care',
      company: 'Wipro',
      firm: purva,
      packing: '250ml',
      mrp: 180.0,
      rate: 145.0,
    ),
    CatalogProduct(
      id: 'wip-pc-2',
      name: 'Yardley London English Lavender Talc',
      category: 'Personal Care',
      company: 'Wipro',
      firm: purva,
      packing: '100g',
      mrp: 120.0,
      rate: 95.0,
    ),
    CatalogProduct(
      id: 'wip-pc-3',
      name: 'Glucovita Bolts Energy Candy',
      category: 'Personal Care',
      company: 'Wipro',
      firm: purva,
      packing: '40g Pocket Pack',
      mrp: 20.0,
      rate: 16.0,
    ),
    CatalogProduct(
      id: 'wip-fc-1',
      name: 'Wipro Safewash Liquid Detergent',
      category: 'Fabric Care',
      company: 'Wipro',
      firm: purva,
      packing: '500ml Bottle',
      mrp: 110.0,
      rate: 88.0,
    ),

    // ==========================================
    // PURVA ENTERPRISES - FENA
    // ==========================================
    CatalogProduct(
      id: 'fen-det-1',
      name: 'Fena Super Detergent Powder',
      category: 'Detergent',
      company: 'Fena',
      firm: purva,
      packing: '1 kg Pack',
      mrp: 85.0,
      rate: 68.0,
    ),
    CatalogProduct(
      id: 'fen-det-2',
      name: 'Fena Super Detergent Cake',
      category: 'Detergent',
      company: 'Fena',
      firm: purva,
      packing: '250g Bar',
      mrp: 20.0,
      rate: 16.0,
    ),
    CatalogProduct(
      id: 'fen-det-3',
      name: 'Fena Smart Wash Liquid Detergent',
      category: 'Detergent',
      company: 'Fena',
      firm: purva,
      packing: '500ml Bottle',
      mrp: 95.0,
      rate: 76.0,
    ),
    CatalogProduct(
      id: 'fen-dish-1',
      name: 'Fena Bipol Dishwash Bar',
      category: 'Dishwash',
      company: 'Fena',
      firm: purva,
      packing: '300g Bar',
      mrp: 25.0,
      rate: 20.0,
    ),
    CatalogProduct(
      id: 'fen-dish-2',
      name: 'Fena Bipol Dishwash Gel',
      category: 'Dishwash',
      company: 'Fena',
      firm: purva,
      packing: '250ml Bottle',
      mrp: 50.0,
      rate: 40.0,
    ),

    // ==========================================
    // PURVA ENTERPRISES - FUNFOOD
    // ==========================================
    CatalogProduct(
      id: 'fun-mayo-1',
      name: 'Funfoods Veg Mayonnaise Original',
      category: 'Mayonnaise',
      company: 'Funfood',
      firm: purva,
      packing: '250g Pouch',
      mrp: 89.0,
      rate: 72.0,
    ),
    CatalogProduct(
      id: 'fun-mayo-2',
      name: 'Funfoods Burger Mayonnaise',
      category: 'Mayonnaise',
      company: 'Funfood',
      firm: purva,
      packing: '250g Pouch',
      mrp: 99.0,
      rate: 80.0,
    ),
    CatalogProduct(
      id: 'fun-mayo-3',
      name: 'Funfoods Garlic Mayonnaise',
      category: 'Mayonnaise',
      company: 'Funfood',
      firm: purva,
      packing: '250g Pouch',
      mrp: 99.0,
      rate: 80.0,
    ),
    CatalogProduct(
      id: 'fun-sauce-1',
      name: 'Funfoods Pizza & Pasta Sauce',
      category: 'Sauces & Dips',
      company: 'Funfood',
      firm: purva,
      packing: '300g Bottle',
      mrp: 99.0,
      rate: 79.0,
    ),
    CatalogProduct(
      id: 'fun-sauce-2',
      name: 'Funfoods Cheesy Dip',
      category: 'Sauces & Dips',
      company: 'Funfood',
      firm: purva,
      packing: '200g Tub',
      mrp: 85.0,
      rate: 68.0,
    ),
    CatalogProduct(
      id: 'fun-spr-1',
      name: 'Funfoods Peanut Butter Crunchy',
      category: 'Spreads',
      company: 'Funfood',
      firm: purva,
      packing: '350g Jar',
      mrp: 165.0,
      rate: 135.0,
    ),
    CatalogProduct(
      id: 'fun-spr-2',
      name: 'Funfoods Veg Sandwich Spread',
      category: 'Spreads',
      company: 'Funfood',
      firm: purva,
      packing: '250g Bottle',
      mrp: 95.0,
      rate: 76.0,
    ),

    // ==========================================
    // PURVA ENTERPRISES - IMAMI
    // ==========================================
    CatalogProduct(
      id: 'pe-ima-hair-1',
      name: 'Navratna Ayurvedic Cool Oil',
      category: 'Hair Care',
      company: 'Imami',
      firm: purva,
      packing: '100ml Bottle',
      mrp: 80.0,
      rate: 65.0,
    ),
    CatalogProduct(
      id: 'pe-ima-hair-2',
      name: 'Navratna Ayurvedic Cool Oil',
      category: 'Hair Care',
      company: 'Imami',
      firm: purva,
      packing: '200ml Bottle',
      mrp: 150.0,
      rate: 122.0,
    ),
    CatalogProduct(
      id: 'pe-ima-hair-3',
      name: 'Emami 7 Oils in One Non Sticky',
      category: 'Hair Care',
      company: 'Imami',
      firm: purva,
      packing: '200ml Bottle',
      mrp: 130.0,
      rate: 105.0,
    ),
    CatalogProduct(
      id: 'pe-ima-skin-1',
      name: 'BoroPlus Antiseptic Cream',
      category: 'Skin Care',
      company: 'Imami',
      firm: purva,
      packing: '40ml Tube',
      mrp: 50.0,
      rate: 40.0,
    ),
    CatalogProduct(
      id: 'pe-ima-skin-2',
      name: 'Fair and Handsome Fairness Cream',
      category: 'Skin Care',
      company: 'Imami',
      firm: purva,
      packing: '60g Tube',
      mrp: 120.0,
      rate: 96.0,
    ),
    CatalogProduct(
      id: 'pe-ima-pain-1',
      name: 'Zandu Balm for Headache & Cold',
      category: 'Health & Pain',
      company: 'Imami',
      firm: purva,
      packing: '25g Bottle',
      mrp: 45.0,
      rate: 36.0,
    ),
    CatalogProduct(
      id: 'pe-ima-pain-2',
      name: 'Zandu Kesari Jivan Revitalizer',
      category: 'Health & Pain',
      company: 'Imami',
      firm: purva,
      packing: '450g Jar',
      mrp: 380.0,
      rate: 310.0,
    ),

    // ==========================================
    // MANAS SALES - RACKET (RECKITT)
    // ==========================================
    CatalogProduct(
      id: 'rac-soap-1',
      name: 'Handwash (Dettol Pump)',
      category: 'Soap & Antiseptic',
      company: 'Racket',
      firm: manas,
      packing: '200ml Pump',
      mrp: 99.0,
      rate: 80.0,
    ),
    CatalogProduct(
      id: 'rac-soap-2',
      name: 'Handwash (Dettol Refill)',
      category: 'Soap & Antiseptic',
      company: 'Racket',
      firm: manas,
      packing: '175ml Pouch',
      mrp: 55.0,
      rate: 44.0,
    ),
    CatalogProduct(
      id: 'rac-soap-3',
      name: 'Dettol Original Bathing Soap',
      category: 'Soap & Antiseptic',
      company: 'Racket',
      firm: manas,
      packing: '100g Bar',
      mrp: 45.0,
      rate: 37.0,
    ),
    CatalogProduct(
      id: 'rac-soap-4',
      name: 'Dettol Antiseptic Liquid',
      category: 'Soap & Antiseptic',
      company: 'Racket',
      firm: manas,
      packing: '110ml Bottle',
      mrp: 72.0,
      rate: 59.0,
    ),
    CatalogProduct(
      id: 'rac-clean-1',
      name: 'Harpic Power Plus Toilet Cleaner',
      category: 'Home Cleaners',
      company: 'Racket',
      firm: manas,
      packing: '500ml Bottle',
      mrp: 95.0,
      rate: 78.0,
    ),
    CatalogProduct(
      id: 'rac-clean-2',
      name: 'Lizol Disinfectant Surface Cleaner',
      category: 'Home Cleaners',
      company: 'Racket',
      firm: manas,
      packing: '500ml Citrus',
      mrp: 110.0,
      rate: 89.0,
    ),
    CatalogProduct(
      id: 'rac-clean-3',
      name: 'Harpic Bathroom Cleaner Trigger',
      category: 'Home Cleaners',
      company: 'Racket',
      firm: manas,
      packing: '500ml Spray',
      mrp: 105.0,
      rate: 85.0,
    ),
    CatalogProduct(
      id: 'rac-pest-1',
      name: 'Mortein Mosquito Repellent Coils',
      category: 'Pest Care',
      company: 'Racket',
      firm: manas,
      packing: 'Pack of 10',
      mrp: 40.0,
      rate: 32.0,
    ),
    CatalogProduct(
      id: 'rac-pest-2',
      name: 'All Out Ultra Mosquito Liquid Refill',
      category: 'Pest Care',
      company: 'Racket',
      firm: manas,
      packing: '45ml Refill',
      mrp: 85.0,
      rate: 68.0,
    ),

    // ==========================================
    // MANAS SALES - IMAMI
    // ==========================================
    CatalogProduct(
      id: 'ms-ima-hair-1',
      name: 'Navratna Cool Oil Original',
      category: 'Hair Care',
      company: 'Imami',
      firm: manas,
      packing: '100ml Bottle',
      mrp: 80.0,
      rate: 65.0,
    ),
    CatalogProduct(
      id: 'ms-ima-hair-2',
      name: 'Kesh King Ayurvedic Medicinal Oil',
      category: 'Hair Care',
      company: 'Imami',
      firm: manas,
      packing: '100ml Bottle',
      mrp: 160.0,
      rate: 130.0,
    ),
    CatalogProduct(
      id: 'ms-ima-skin-1',
      name: 'BoroPlus Antiseptic Cream',
      category: 'Skin Care',
      company: 'Imami',
      firm: manas,
      packing: '40ml Tube',
      mrp: 50.0,
      rate: 40.0,
    ),
    CatalogProduct(
      id: 'ms-ima-skin-2',
      name: 'BoroPlus Aloe Fresh Gel',
      category: 'Skin Care',
      company: 'Imami',
      firm: manas,
      packing: '150ml Tub',
      mrp: 90.0,
      rate: 72.0,
    ),
    CatalogProduct(
      id: 'ms-ima-hlth-1',
      name: 'Zandu Chyawanprash Avaleha',
      category: 'Healthcare',
      company: 'Imami',
      firm: manas,
      packing: '500g Jar',
      mrp: 210.0,
      rate: 170.0,
    ),
    CatalogProduct(
      id: 'ms-ima-hlth-2',
      name: 'Fast Relief Herbal Spray',
      category: 'Healthcare',
      company: 'Imami',
      firm: manas,
      packing: '50ml Can',
      mrp: 135.0,
      rate: 110.0,
    ),

    // ==========================================
    // MANAS SALES - DABAR (DABUR)
    // ==========================================
    CatalogProduct(
      id: 'dab-oral-1',
      name: 'Dabur Red Ayurvedic Toothpaste',
      category: 'Oral Care',
      company: 'Dabar',
      firm: manas,
      packing: '150g Tube',
      mrp: 95.0,
      rate: 76.0,
    ),
    CatalogProduct(
      id: 'dab-oral-2',
      name: 'Dabur Meswak Herbal Toothpaste',
      category: 'Oral Care',
      company: 'Dabar',
      firm: manas,
      packing: '100g Tube',
      mrp: 75.0,
      rate: 60.0,
    ),
    CatalogProduct(
      id: 'dab-oral-3',
      name: 'Dabur Babool Clove Toothpaste',
      category: 'Oral Care',
      company: 'Dabar',
      firm: manas,
      packing: '175g Tube',
      mrp: 60.0,
      rate: 48.0,
    ),
    CatalogProduct(
      id: 'dab-hlth-1',
      name: 'Dabur 100% Pure Honey Squeezy',
      category: 'Health & Wellness',
      company: 'Dabar',
      firm: manas,
      packing: '250g Bottle',
      mrp: 130.0,
      rate: 105.0,
    ),
    CatalogProduct(
      id: 'dab-hlth-2',
      name: 'Dabur Chyawanprash Immunity Booster',
      category: 'Health & Wellness',
      company: 'Dabar',
      firm: manas,
      packing: '500g Jar',
      mrp: 240.0,
      rate: 195.0,
    ),
    CatalogProduct(
      id: 'dab-hlth-3',
      name: 'Honitus Ayurvedic Cough Syrup',
      category: 'Health & Wellness',
      company: 'Dabar',
      firm: manas,
      packing: '100ml Bottle',
      mrp: 90.0,
      rate: 72.0,
    ),
    CatalogProduct(
      id: 'dab-hair-1',
      name: 'Dabur Amla Hair Oil Thick & Dark',
      category: 'Hair Care',
      company: 'Dabar',
      firm: manas,
      packing: '180ml Bottle',
      mrp: 95.0,
      rate: 76.0,
    ),
    CatalogProduct(
      id: 'dab-hair-2',
      name: 'Vatika Enriched Coconut Hair Oil',
      category: 'Hair Care',
      company: 'Dabar',
      firm: manas,
      packing: '150ml Bottle',
      mrp: 85.0,
      rate: 68.0,
    ),

    // ==========================================
    // MANAS SALES - CADBURY
    // ==========================================
    CatalogProduct(
      id: 'cad-choc-1',
      name: 'Cadbury Dairy Milk Chocolate',
      category: 'Chocolates',
      company: 'Cadbury',
      firm: manas,
      packing: '50g Bar',
      mrp: 45.0,
      rate: 37.0,
    ),
    CatalogProduct(
      id: 'cad-choc-2',
      name: 'Cadbury Dairy Milk Silk Plain',
      category: 'Chocolates',
      company: 'Cadbury',
      firm: manas,
      packing: '60g Bar',
      mrp: 85.0,
      rate: 70.0,
    ),
    CatalogProduct(
      id: 'cad-choc-3',
      name: 'Cadbury 5 Star Caramel Bar',
      category: 'Chocolates',
      company: 'Cadbury',
      firm: manas,
      packing: '20g Bar',
      mrp: 10.0,
      rate: 8.0,
    ),
    CatalogProduct(
      id: 'cad-choc-4',
      name: 'Cadbury Perk Chocolate Wafer',
      category: 'Chocolates',
      company: 'Cadbury',
      firm: manas,
      packing: '15g Pack',
      mrp: 10.0,
      rate: 8.0,
    ),
    CatalogProduct(
      id: 'cad-bev-1',
      name: 'Cadbury Bournvita Nutrition Jar',
      category: 'Beverages',
      company: 'Cadbury',
      firm: manas,
      packing: '500g Jar',
      mrp: 240.0,
      rate: 198.0,
    ),
    CatalogProduct(
      id: 'cad-bev-2',
      name: 'Cadbury Bournvita Refill Pack',
      category: 'Beverages',
      company: 'Cadbury',
      firm: manas,
      packing: '1 kg Refill',
      mrp: 430.0,
      rate: 355.0,
    ),
    CatalogProduct(
      id: 'cad-bev-3',
      name: 'Cadbury Hot Chocolate Drink Mix',
      category: 'Beverages',
      company: 'Cadbury',
      firm: manas,
      packing: '200g Tub',
      mrp: 160.0,
      rate: 130.0,
    ),
    CatalogProduct(
      id: 'cad-bisc-1',
      name: 'Oreo Vanilla Creme Sandwich Biscuits',
      category: 'Biscuits',
      company: 'Cadbury',
      firm: manas,
      packing: '120g Pack',
      mrp: 35.0,
      rate: 28.0,
    ),
    CatalogProduct(
      id: 'cad-bisc-2',
      name: 'Bournvita Crunchy Chocolate Cookies',
      category: 'Biscuits',
      company: 'Cadbury',
      firm: manas,
      packing: '120g Pack',
      mrp: 35.0,
      rate: 28.0,
    ),

    // ==========================================
    // MANAS SALES - GOWARDHAN
    // ==========================================
    CatalogProduct(
      id: 'gow-ghee-1',
      name: 'Gowardhan 100% Pure Cow Ghee',
      category: 'Ghee & Butter',
      company: 'Gowardhan',
      firm: manas,
      packing: '500ml Jar',
      mrp: 365.0,
      rate: 315.0,
    ),
    CatalogProduct(
      id: 'gow-ghee-2',
      name: 'Gowardhan 100% Pure Cow Ghee',
      category: 'Ghee & Butter',
      company: 'Gowardhan',
      firm: manas,
      packing: '1 Litre Pouch',
      mrp: 690.0,
      rate: 595.0,
    ),
    CatalogProduct(
      id: 'gow-ghee-3',
      name: 'Gowardhan Pasteurized Table Butter',
      category: 'Ghee & Butter',
      company: 'Gowardhan',
      firm: manas,
      packing: '100g Block',
      mrp: 58.0,
      rate: 49.0,
    ),
    CatalogProduct(
      id: 'gow-dairy-1',
      name: 'Go Cheese Plain Slices (10 Slices)',
      category: 'Dairy & Cheese',
      company: 'Gowardhan',
      firm: manas,
      packing: '200g Pack',
      mrp: 155.0,
      rate: 128.0,
    ),
    CatalogProduct(
      id: 'gow-dairy-2',
      name: 'Go Pizza Cheese Shredded Mozzarella',
      category: 'Dairy & Cheese',
      company: 'Gowardhan',
      firm: manas,
      packing: '200g Pouch',
      mrp: 140.0,
      rate: 115.0,
    ),
    CatalogProduct(
      id: 'gow-dairy-3',
      name: 'Gowardhan Fresh Malai Paneer',
      category: 'Dairy & Cheese',
      company: 'Gowardhan',
      firm: manas,
      packing: '200g Block',
      mrp: 95.0,
      rate: 80.0,
    ),
  ];

  static List<String> getCompanies(String firm) {
    return companiesByFirm[firm] ?? [];
  }

  static List<String> getCategories(String firm, String company) {
    final products = catalog.where(
      (p) => p.firm == firm && p.company.toLowerCase() == company.toLowerCase(),
    );
    final categories = <String>{};
    for (final p in products) {
      categories.add(p.category);
    }
    return categories.toList();
  }

  static List<CatalogProduct> getProducts({
    required String firm,
    required String company,
    String? category,
  }) {
    return catalog.where((p) {
      final firmMatch = p.firm == firm;
      final compMatch = p.company.toLowerCase() == company.toLowerCase();
      final catMatch = category == null || category.isEmpty || p.category == category;
      return firmMatch && compMatch && catMatch;
    }).toList();
  }
}
